site_name: Django Commons
repo_url: https://github.com/django-commons/django-commons.github.io
markdown_extensions:
  - toc:
      permalink: "#"
theme:
  name: material
nav:
  - Home: index.md
  - FAQ: faq.md
  - Funding: funding.md
  - Governance: governance.md
  - Media: media.md
  - Team: team.md
  - Values: values.md
